name: lged_inspection
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  fl_chart: ^0.55.0
  hive: ^2.2.3
  hive_flutter:
  hive_generator:
  build_runner:
  dropdown_button2: ^1.7.1
  animated_bottom_navigation_bar: ^1.0.1
  image_picker: ^0.8.4+11
  animated_button_bar: ^0.0.2
  font_awesome_flutter: ^10.1.0
  firebase_messaging: ^13.0.0
  firebase_core: ^1.21.1
  dropdown_search: ^5.0.1
  path: ^1.8.1
  sqflite: ^2.0.3+1
  sizer: ^2.0.15
  flutter: 
    sdk: flutter

  path_provider: ^2.0.11

  shared_preferences: ^2.0.15





dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter:
  assets:
    - assets/image/
    -
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"

